# Generated by Django 4.0 on 2022-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_anyfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anyfile',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='anyfile',
            name='category',
            field=models.CharField(choices=[('CVM', 'curriculum'), ('ANY', 'any file'), ('IMG', 'image')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anyfile',
            name='file',
            field=models.FileField(upload_to='public/file/%Y/%m/%d'),
        ),
    ]
